%% Control Design
% Written By Konur Yigit
% Error Dynamics
Ae = [0, 1, 0, 0;0, ...
    -(2*EOL_Vehicle_Cf+2*EOL_Vehicle_Cr)/(EOL_Vehicle_M*EOL_Vehicle_Speed), ...
     (2*EOL_Vehicle_Cf+2*EOL_Vehicle_Cr)/(EOL_Vehicle_M), ...
     (-2*EOL_Vehicle_Cf*EOL_Vehicle_lf+2*EOL_Vehicle_Cr*EOL_Vehicle_lr) ...
     /(EOL_Vehicle_M*EOL_Vehicle_Speed); ...
     0,0,0,1; ...
     0, ...
     (-2*EOL_Vehicle_Cf*EOL_Vehicle_lf+2*EOL_Vehicle_Cr*EOL_Vehicle_lr) ...
     /(EOL_Vehicle_Iz*EOL_Vehicle_Speed), ...
     (2*EOL_Vehicle_Cf*EOL_Vehicle_lf-2*EOL_Vehicle_Cr*EOL_Vehicle_lr) ...
     /(EOL_Vehicle_Iz), ...
     -(2*EOL_Vehicle_Cf*EOL_Vehicle_lf^2+2*EOL_Vehicle_Cr*EOL_Vehicle_lr^2) ...
     /(EOL_Vehicle_Iz*EOL_Vehicle_Speed)];

B1e=  [0; ...
       2*EOL_Vehicle_Cf/EOL_Vehicle_M; ...
       0;
       2*EOL_Vehicle_Cf*EOL_Vehicle_lf/EOL_Vehicle_Iz];

B2e= [0; ...
     -(EOL_Vehicle_Speed+ ...
     ((2*EOL_Vehicle_Cf*EOL_Vehicle_lf-2*EOL_Vehicle_Cr*EOL_Vehicle_lr) ...
     /(EOL_Vehicle_M*EOL_Vehicle_Speed))); ...
     0; ...
     -(2*EOL_Vehicle_Cf*EOL_Vehicle_lf^2+2*EOL_Vehicle_Cr*EOL_Vehicle_lr^2) ...
     /(EOL_Vehicle_Iz*EOL_Vehicle_Speed)];

controlrank = rank(ctrb(Ae,B1e));% controllability matrix rank.
% Check If rank equals to 4.
if controlrank==4
    disp("Control Rank is Full");
end
Ce = eye(4);
Ces= [1 0 0 0];
De  = 0;
control_sys = ss(Ae,B1e,Ce,De);
control_syss= ss(Ae,B1e,Ces,De);
% Discrete Formulation

control_sysd= c2d(control_sys,0.01,"zoh");
% Tuning Parameters
Q1 = [2000 0 0 0;0 250 0 0;0 0 3500 0;0 0 0 100];
Q2 = [20 0 0 0;0 0.5 0 0;0 0 38.5 0;0 0 0 20.5];
Q = Q2;
R = 5;
Qs= [1750 0 0 0 0;0 250 0 0 0;0 0 2500 0 0;0 0 0 100 0;0 0 0 0 1];
Kgain = lqr(control_sys,Q,R);
Ksgain= lqi(control_syss,Qs,R);
Kdgain= lqrd(control_sysd.A,control_sysd.B,Q,R,0.01);
% closed Loop Formulation (continuous)
Acl = Ae-B1e*Kgain;
Bcl = B2e;
Ccl = eye(4);
Dcl   = zeros(4,1);

% Closed Loop Formulation (discrete)
Acld = control_sysd.A - control_sysd.B*Kdgain;
Bcld = B2e;
Ccld  = eye(4);
Dcld  = zeros(4,1);
dt   = 0.01;
